import Vue from 'vue'
import Vuel18n from 'vue-i18n'

Vue.use(Vuel18n)

export const i18n = new Vuel18n({
    locale: 'es',
    fallbackLocale: 'en',
    messages:{
        es:{
            /* Hotlinks */
            expf: 'Explorar Fondos',
            exps: 'Explorar Servicios',
            expp: 'Preguntas Frecuentes',
            subsbtn: 'Suscríbete',

            navB: 'EMPRESA',
            navBD1: '¿Por qué PER CAPITAL?',
            navBD2: 'Equipo',
            navBD3: 'Gobierno Corporativo',
            navBD4: 'Contacto',

            navF: 'FONDOS',
            navFD1: 'Fondo Mutual',
            navFD2: 'Fondo Inmobiliario',
            navFD3: 'Capital de riesgo',

            navS: 'SERVICIOS',
            navR: 'REPORTES',
            navRD1: 'Trimestral',
            navRD2: 'Anual',

            navT: 'HERRAMIENTAS',
            navtD1: 'Calculadoras',
            navtD2: 'Estrategias',
            navtD3: 'Noticias',
            navtD4: 'Calendario bancario',

            /* Finally you can start */
            start: 'FINALMENTE PUEDES EMPEZAR',
            startdesc: 'PER CAPITAL ofrece fácil acceso a oportunidades de inversión Premium en el mercado de Capitales, Inmobiliario y de Capital de Riesgo, previamente evaluadas y aprobadas por nuestros expertos, para inversionistas institucionales y público en general.',
            strans: 'TRANSPARENCIA',
            stransd: 'Somos una empresa regulada y cumplimos con los mayores estándares de cumplimiento para garantizar la tranquilidad a nuestros clientes.',
            sanali:'ANÁLISIS RIGUROSO',
            sanalid: 'Nuestro equipo investiga y analiza para ti, hasta el más mínimo detalle de cada proyecto de inversión que ofrecemos.',
            sfinance: 'FINANZAS INTELIGENTES',
            sfinanced: 'Estudiamos a fondo los proyectos y mercados buscando solvencia financiera, reputacional y excelencia en gestión empresarial con el objetivo de generar valor. ',
            scomunidad: 'COMUNIDAD INVERSIONISTA',
            scomunidadd: 'Construimos una comunidad de inversionistas institucionales y no institucionales que ofrece una alternativa de financiamiento.',
        
            /* Numbers */
            numbers: 'LOS NÚMEROS CUENTAN',
            indicators: 'Indicadores',
            pib: 'PIB (%)',
            pob: 'Población (MM)',
            ri: 'Reservas Internacionales (MM)',
            tc: 'Tasa de Cambio Bs/$',
            te: 'Tasa de Cambio Bs/€',
            co: 'Cesta OPEP',
            cv: 'Cesta Venezolana',
            sources: 'Fuentes',

            /* Calculators */
            calculators: 'CALCULADORAS',
            roi: 'Rentabilidad de inversión',
            ii: 'Inversión inicial',
            vf: 'Valor final',
            y: 'Años',
            validationY: 'El dato ingresado debe ser numérico, entero, mayor a cero',
            result: 'EL ROI de la inversión es:',
            btncalculate: 'Calcular',
            so: 'Objetivo de Ahorro',
            ia: 'Interés Anual',
            p:'Periodicidad',
            validationP: 'Seleccione periodicidad',
            resultso: 'Para conseguir el objetivo de ahorro cada mes debes invertir',

            /* News */
            news: 'NOTICIAS',

            /* Contact */
            contact: 'CONTACTO',
            location: 'UBICACIÓN',
            phone: 'TELÉFONO',
            email: 'CORREO ELECTRÓNICO',

            /* Footer */
            fservicesd1: 'Administración E.I.C',
            fservicesd2: 'Asesoría Financiera',
            fservicesd3: 'Estructuración',
            fservicesd4: 'Ingeniería financiera',
            f1: 'PER CAPITAL Sociedad Administradora de Entidades de Inversión Colectiva C.A., RIF J-41280239-9 es una empresa autorizada y regulada por la SUNAVAL',
            f2: 'PER CAPITAL Fondo Mutual de Capital Abierto C.A., es una empresa autorizada y regulada por la SUNAVAL',
            f3: 'PER CAPITAL Asesora de Inversión, RIF J-41296024-5 es una empresa autorizada y regulada por la SUNAVAL',
            f4: 'PER CAPITAL sociedad Administradora de E.I.C. C.A. y los Fondos que ofrece son regulados y han sido autorizados por la SUNAVAL. Los prospectos, información clave, contabilidad y reportes periódicos, así como otros documentos de la sociedad y los fondos que administra pueden ser obtenidos en las oficinas del distribuidor. Si usted es un inversionista Privado no',
            f5: 'debe',
            f6: 'tomar la información contenida en este sitio web como una recomendación o sugerencia que afecte su decisión de inversión. Nada en este sitio web debe ser tomado como una asesoría o consejo financiero. Cada inversionista debe informarse del prospecto, estados financieros y política de inversión antes de invertir. El contenido de este sitio web ha sido preparado basándose en los resultados del análisis de información cuidadosamente levantada, con la opinión de que es confiable para el momento que fue publicada. Las opiniones y visiones presentadas son de PER CAPITAL y pueden cambiar. PER CAPITAL hace uso de las técnicas más adecuadas para asegurar que la información presentada es precisa. Sin embargo, pueden ocurrir errores u omisiones fuera de nuestro control. Bajo ninguna circunstancia se permite la copia o distribución de la información aquí presentada. ',
            f7: 'Asesoría:',
            f8: 'Nada en este sitio web debe ser considerado como asesoría financiera personal. ',
            f9: 'Desempeño:',
            f10: 'El desempeño histórico no determina el desempeño a futuro. ',
            f11: 'Fluctuaciones:',
            f12: 'El valor de los activos pertenecientes a los fondos puede subir o bajar ocasionando fluctuaciones en el valor de la unidad de inversión. ',
            f13: 'Riesgos:',
            f14: 'Existen riesgos asociados a las inversiones y la perdida de capital es posible.',
            f15: 'No debe suponerse ni debe asegurarse que las operaciones recomendadas producirán efectivamente los beneficios actualmente estimados, ni que los respectivos valores tendrán en el futuro un comportamiento similar a aquel que fundamento la presente recomendación',
            f16: 'Normas Relativas a la Autorización y Registro de los Corredores Públicos de Valores y Asesores de Inversión. Sección V, Articulo 28.',
            f17: 'Existen riesgos asociados con las inversiones, la pérdida del principal del capital es posible. Algunas restricciones aplican. ',
        
            /* Why */
            why: '¿POR QUÉ',
            whydesc: 'Somos un equipo de trabajo de comprobada experiencia en inversiones y desarrollo de negocios en la búsqueda de hacer crecer el patrimonio mediante la creación de valor. ',
            w1: 'ESCOGE ENTRE INVERSIONES DISEÑADAS PARA FÁCIL SALIDA',
            w1d: 'Desde los Fondos Mutuales hasta Fondos Inmobiliarios, nuestro equipo de expertos revisa a profundidad cada detalle y hace la debida diligencia para su presentación al público.',
            w1d1: 'Nuestro objetivo es lograr dar facilidades de entrada y salida de las inversiones a nuestros clientes. ',
            w2: 'SUPERVISIÓN, CONTROL Y TRANSPARENCIA FINANCIERA',
            w2d: 'Mantenemos evaluación continua de los activos representados en la cartera de inversiones, para asegurar que estén apegadas al plan de negocio.',
            w2d1: 'Los fondos mutuales son monitoreados diariamente para tomar las decisiones que mitiguen riesgos y rentabilicen el capital. Reportes periódicos son emitidos para mantener informados a nuestros clientes. ',
            w3: 'EXPERIENCIA Y CONOCIMIENTO',
            w3d1: 'Nuestro equipo tiene una amplia y exitosa experiencia en las inversiones.',
            w3d2: 'Desarrollamos estrategias de cobertura de riesgo para protegernos de crisis financieras, políticas y naturales.',
            w3d3: 'Sabemos dónde invertir, como maximizar ganancias y minimizar los riesgos, evitando las disminuciones abruptas de capital. ',
        
        
            /* Team */
            teamdesc: 'Nuestra experiencia colectiva de más de 40 años, así como el amplio conocimiento en finanzas, mercados, ingeniería financiera y desarrollo de negocios, te da una ventaja a la hora de elegir la inversión más idónea para ti con el fin de maximizar el potencial de tu capital controlando y minimizando los riesgos asociados. ',
            gg: 'GERENTE GENERAL',
            ggd: 'Administrador Mención Banca y Finanzas y Asesor de Inversión autorizado con más de 17 años de experiencia en finanzas, ingeniería financiera, desarrollo de negocios y estructuración en mercado local e internacional.',
            f: 'FINANZAS ',
            fd: 'Administrador y Asesor de Inversión autorizado con más de 17 años de experiencia en banca y finanzas, mercado de capitales, trading, manejo de portafolio y cobertura de riesgo.',
            ac: 'ADMINISTRACIÓN Y CONTROL ',
            acd: 'C.P.C. y Asesor de Inversión autorizado con más de 15 años de experiencia en auditoría contable y financiera, proyección de estados financieros, valoración de empresas y administración de activos financieros.',
            fc: 'FINANZAS CORPORATIVAS ',
            fcd: 'Economista, Corredor Publico de títulos Valores y Asesor de Inversión autorizado por la SUNAVAL con más de 30 años de experiencia en gestión de portafolio, evaluación de proyectos, estructuración de deuda y capital.',
            l: 'LEGAL',
            ld: 'Abogado con más de 20 años de experiencia en control y regulación, gestiones públicas y desarrollo de proyectos.',
            team: 'EQUIPO',

            /* Corporate */
            corporate:'GOBIERNO CORPORATIVO',
            corporatedesc: 'El marco del gobierno corporativo de PER CAPITAL es un conjunto de principios, guías y prácticas que apoyan la sustentabilidad del desempeño y la creación de valor para nuestros inversionistas en el largo plazo. Nuestro compromiso con el buen proceder, es integral para nuestro negocio y refleja no solo el apego a las regulaciones y los mejores estándares del mercado sino también, eficiencia en liderazgo de nuestra gerencia. ',
            g1: 'Guía de Gobierno Corporativo',
            g1d: 'Pautas de gobierno corporativo 2019',
            g2: 'Código de conducta y ética empresarial',
            g2d: 'Pautas de gobierno corporativo 2019',
            btndownload: 'Descargar',

            /* Faq */
            faqtit: 'PREGUNTAS FRECUENTES',
            faqhelp: 'Haga click sobre una pregunta para visualizar respuesta',
            q1: '¿Qué es una Sociedad Administradora de E.I.C?',
            r1: 'Son empresas autorizadas por la SUNAVAL que tienen por objeto administrar el patrimonio de las entidades de inversión colectiva, cualquiera sea su tipo, y representar a los mismos de acuerdo con los términos del contrato de administración que celebren al efecto. ',
            r1c: 'Características',
            r1cl: 'No pueden administrar a dos E.I.C. iguales',
            r1cl1: 'Invierten recursos en nombre y por cuenta de las E.I.C.',
            r1cl2: 'Cobran comisiones por servicios prestados y son fijadas por mutuo acuerdo con E.I.C.',
            r1cl3: 'Llevan contabilidad separada de las E.I.C.',
            r1cl4: 'Llevan contabilidad de las E.I.C.',
            r1cl5: 'Informar trimestralmente a inversionistas de las E.I.C. (estado y comportamiento de mercado)',
            r1cl6: 'Reflejar en la rentabilidad de las E.I.C. que administren rentabilidad menos gastos y remuneraciones/comisiones',
            r1np: 'No pueden',
            r1npl: 'Garantizar resultados o rendimientos específicos',
            r1npl1: 'Dar o tomar dinero prestado de las E.I.C.',
            r1npl2: 'Mantener custodia títulos valores al portador de las E.I.C.',
            r1npl3: 'Otorgar garantías personales o reales para asegurar obligaciones a terceros',
            r1m: 'Deben',
            r1ml: 'Distribuir UDI de las E.I.C. ',
            r1ml1: 'Invertir recursos a nombre y cuenta de la E.I.C.',
            r1ml2: 'Mantener evaluación continua de los valores de la E.I.C.',
            r1ml3: 'Asegurar que la E.I.C. tenga flujo de caja para responder obligaciones y gastos',
            r1ml4: 'Coordinar servicios legales, contables y de distribución de las E.I.C.',
            r1ml5: 'Prepara prospectos, reportes e informes relacionados para inversionistas y SUNAVAL',
            r1ml6: 'Controlar servicio de agente de traspaso y suministrar información a agente custodio para transferencia de valores o efectivo.',
            r1ml7: 'Representar legalmente a las E.I.C.',
            r1ml8: 'Recomprar UDI',
            r1ml9: 'Calcular diariamente el valor del cativo neto de los fondos mutuales y de su UDI',
            r1ml10: 'Llevar registro de inversionistas y sus operaciones',
            r1ca: 'Pueden',
            r1cal: 'Retirar fondos de la E.I.C. y su Sociedad Administradora para pagar gastos, recompra y pago de dividendos',
            r1cal1: 'Actuar como Asesores de Inversión, Agentes de Traspaso',
            q2: '¿Qué es una E.I.C?',
            r2: 'Son entidades autorizadas por la SUNAVAL que canalizan los aportes de inversionistas destinados a constituir un capital común, integrado por una cartera de títulos valores u otros activos. ',
            r2p: 'Pueden constituir patrimonio mediante fideicomiso.',
            r2p2: 'Inversionistas son personas naturales o jurídicas con unidades de inversión.',
            r2p3: 'Unidades de Inversión son acciones, cuotas, participaciones u otro instrumento que emite la E.I.C.',
            r2c: 'Establecer Política de Inversión',
            r2c1: 'Definir Política de Distribución de Utilidades (capitalizar o pagar)',
            r2c2: 'Tener comité de inversión designado por la entidad o por la sociedad administradora',
            r2c3: 'Comité de inversión toma decisiones de inversión',
            r2c4: 'Miembros de Comité de Inversión puede ser designados por E.I.C. o por Sociedad Administradora ',
            r2c5: 'Deben celebrar asamblea de inversionistas',
            r2c6: 'Inversionistas pueden ser representados mediante carta poder expresando facultades otorgadas',
            q3: '¿Qué es un Fondo Mutual de Capital Abierto?',
            r3: 'Es una E.I.C. que tiene por objeto la inversión en títulos valores, con arreglo al principio de distribución de riesgos.',
            r3c: 'UDI no transferibles ni se inscriben en Bolsa (puede emitir fracciones de UDI)',
            r3c1: 'Puede aumentar capital o patrimonio por aporte de inversionistas o puede disminuir patrimonio o capital por retiro de inversionistas, sin necesidad de asamblea de inversionistas.',
            r3c2: 'Debe distribuir en su totalidad los rendimientos netos a inversionistas (en efectivo o capitalizando)',
            r3p: 'Pueden invertir en títulos ',
            r3p1: 'Cuya oferta pública haya sido autorizada por la Comisión Nacional de Valores',
            r3p2: 'Los inscritos en las bolsas de valores',
            r3p3: 'Los que hayan sido emitidos o avalados por la República u otras instituciones de derecho público',
            r3p4: 'Que hayan sido emitidos de conformidad con la Ley del Banco Central de Venezuela',
            r3p5: 'Los que hayan sido emitidos por instituciones regidas por la Ley General de Bancos y otras Instituciones Financieras',
            r3p6: 'Los emitidos de acuerdo a la Ley del Sistema Nacional de Ahorro y Préstamo',
            r3b: 'Quedan',
            r3b2: 'exentos del impuesto sobre la renta los enriquecimientos netos obtenidos por las entidades de inversión colectiva y del impuesto causado',
            r3b3: 'de acuerdo a lo previsto en la Ley del Impuesto al Activo Empresarial.',
            q4: '¿Qué es un Fondo Inmobiliario?',
            r4: 'Son aquellos cuyo objeto sea la canalización de recursos hacia proyectos del sector inmobiliario y de bienes raíces. ',
            q5: '¿Por que debería invertir en PER CAPITAL?',
            r5: 'Acceso a oportunidades de inversión que antes eran solo para inversionistas calificados de alto patrimonio.',
            r51: 'Beneficio de la experiencia y conocimiento de nuestros analistas y equipo de expertos.',
            r52: 'Puedes empezar tu inversión con el mínimo requerido.',
            q6: '¿Cuáles son los riesgos?',
            r6: 'Cualquier inversión conlleva riesgos asociados al mercado en el que se desarrolla. Esto se debe a fluctuaciones en el mercado, variables que no pueden ser controladas o faltas en el cumplimiento de planes de negocio. ',
            r6p: 'PER CAPITAL evalúa con anticipación los posibles escenarios para tratar de mitigar la mayor cantidad de riesgos posibles y así evitar pérdidas. ',
            r6p2: 'Sin embargo, es posible que los riesgos superen las medidas de contingencia tomadas y la perdida de capital es probable. ',
            q7: '¿Cuál es la inversión ideal para mi?',
            r7: 'Los inversionistas pueden elegir de la cartera de productos de PER CAPITAL el fondo o inversión que más se ajuste a sus metas financieras. Además, PER CAPITAL cuenta con el servicio de sus expertos para orientarte en el producto que más se adecue a tus objetivos de inversión. ',
            q8: '¿Cuál es la inversión mínima?',
            r8: 'La inversión mínima dependerá del Fondo que el cliente escoja. Normalmente la inversión mínima es de 1 Unidad de Inversión ',
            q9: '¿Cuáles son las comisiones?',
            r9i: 'Inversionistas',
            r9i1: 'Comisión de entrada: 2.5% al suscribir',
            r9i2: 'Comisión de salida: 0%',
            r9e: 'E.I.C.',
            r9e1: 'Comisión de Administración Fondo Mutual: max 5% del valor promedio del activo neto al cierro',
            r9e2: 'Comisión Administración E.I.C. Inmobiliario: max 5% del valor promedio del activo neto al cierre',
            r9e3: 'Comisión Administración E.I.C. Capital de Riesgo: max 10% del valor promedio del activo neto al cierre',
            q10: '¿Una vez colocada mi inversión como puedo verla?',
            r10: 'El cliente obtendrá un certificado por sus Unidades de Inversión y podrá ver el detalle a través de nuestra página web. ',
            q11: '¿Qué requisitos debo presentar si soy un inversionista extranjero (no residente)?',
            r11: 'Todo inversionista extranjero, bien sea Persona Natural o Jurídica debe solicitar al SENIAT un “RIF de No Residente” al correo',
            r11n: 'y presentarlo adicional a los recaudos generales.',


            /* Mutual */
            mutual: 'FONDO MUTUAL DE INVERSIÓN DE CAPITAL ABIERTO',
            mutuall: 'V.U.I',
            goal: 'OBJETIVO',
            goaldesc: 'El fondo PER CAPITAL Fondo Mutual de Inversión de Capital Abierto tiene como objetivo producir un crecimiento de capital a mediano y largo plazo. Invierte principalmente en acciones de compañías que cotizan, se negocian e incorporan a la Bolsa de Valores de Caracas, hacen negocio y se domicilian',
            goaldesc2: 'en Venezuela así como en títulos de deuda corporativos. Las inversiones pueden ser directas o indirectas y el precio de las unidades de Inversión puede variar debido a los movimientos de precio de los títulos que conforman el portafolio.',
            info: 'INFORMACIÓN DE INTERÉS',
            info1: 'Fecha inicio',
            info2: 'Comparativo',
            info3: 'Sector de inversión',
            info4: 'Pricing',
            info5: 'Inversión mínima',
            info5pill: '1 Unidad de Inversión',
            info4pill: '14:00 diario',
            risks: 'RIESGOS',
            risk1: 'Los mercados objeto de inversión pueden subir o bajar de precio y las condiciones del mercado pueden cambiar rápidamente. Debido a esto el valor de las Unidades de Inversión de un fondo pueden variar de la misma manera. ',
            rg: 'GENERAL',
            risk2: 'La custodia de instrumentos financieros involucra riesgo de pérdida en caso de que el custodio se vuelva insolvente o incumpla sus deberes formales. El custodio de las Unidades de Inversión es la',
            risk2a: 'Caja Venezolana de Valores',
            custody: 'CUSTODIA',
            risk3: 'El fondo está expuesto al riesgo de un único mercado y de una sola moneda.',
            country: 'PAÍS',
            risk4: 'El fondo tiene exposición a monedas extranjeras por lo que los cambios en las tasas de cambio pueden producir aumentos o disminución del valor de la inversión y las ganancias obtenidas. ',
            coin: 'MONEDA/CAMBIARIO',
            volatil: 'VOLATILIDAD',
            risk5: 'El precio de la Unidad de Inversión del fondo puede variar debido al movimiento de precio de los activos que lo componen. ',
            howt: '¿CÓMO INVERTIR?',
            howtd: 'Invertir es ahora sencillo con PER CAPITAL, solo siga los siguientes pasos y empiece a sembrar su futuro ahora. ',
            pi: 'Perfil de inversionista',
            pid: 'Determine su perfil de inversionista tomando en cuenta si es Persona Natural o Jurídica, edad, profesional, no profesional y su aversión al riesgo (bajo, mediano, alto)',
            pli: 'Plazo de inversión',
            plid: 'Seleccione el plazo deseado para su inversión (corto, mediano o largo)',
            fund: 'Fondo',
            fundd: 'Seleccione el fondo de su preferencia que se ajuste más a sus objetivos',
            register: 'Regístrate',
            registerd: 'Adquiera las unidades de inversión deseadas del fondo seleccionado completando el proceso de cumplimiento y envío de fondos para la adquisición. ',
            clickhere: 'Haga clic aquí',
            footer: 'También puede solicitar el Prospecto y la Información de Interés para Inversionistas la cual le será enviada vía e mail en donde encontrará el procedimiento para empezar ',
            cfooter:'Contacto:',
            btnprospect: 'PROSPECTO',
            btnreports: 'REPORTES',
            btnsubscribe: 'REGISTRATE',
            btnsubscribe2: 'SUSCRÍBETE',

            /* Services */
            a1tit: 'ADMINISTRACIÓN DE E.I.C.',
            a1: 'Las Entidades de Inversión Colectiva (E.I.C) o Fondos son una manera de canalizar el capital de inversionistas como un patrimonio común para el desarrollo de distintos proyectos con el objetivo de obtener rendimiento. ',
            a11: 'PER CAPITAL cuenta con la autorización del regulador para la administración de E.I.C. y pone a su disposición su experiencia y equipo especializado para: ',
            a1l1: 'Estructuración de Fondos y E.I.C.',
            a1l2: 'Administración de Fondos y E.I.C.',
            a12: 'Estructuramos, administramos y colocamos E.I.C., cubriendo riesgos, velando por la custodia y titularidad de los activos relacionados, generando valor para nuestros clientes. ',
            a2tit: 'ASESORÍA FINANCIERA',
            a2: 'Somos una institución regulada y autorizada para prestar servicios de Asesoría; contamos con profesionales de comprobada experiencia, certificados como Asesores de Inversión y dispuestos a brindar el mejor servicio.',
            a21: 'Nuestro equipo se enfoca en ser guía en el proceso de evaluación y asesoramiento para el manejo patrimonial a nivel: ',
            a2l1: 'Financiero',
            a2l2: 'Legal',
            a2l3: 'Contable',
            a2l4: 'Fiscal',
            a22: 'Enfocados en la obtención de resultados con riesgos controlados. Ayudamos a nuestros clientes a lograr sus metas financiera',
            a3tit: 'ESTRUCTURACIÓN',
            a3: 'Realizamos proyectos de (re) estructuración, emisión y colocación de: ',
            a3l1: 'Renta fija',
            a3l2: 'Renta variable',
            a3l3: 'Nuestra metodología de trabajo consta de 4 pasos: ',
            a3l4: 'Información, diagnóstico y evaluación',
            a3l5: 'Autorización de organismos competentes',
            a3l6: 'Actividades posteriores a inscripción',
            a3l7: 'Colocación',
            a32: 'Nos apoyamos en nuestra red de aliados en el mercado de capitales local e internacional.',
            a4tit: 'INGENIERÍA FINANCIERA',
            a4: 'Ofrecemos soluciones financieras para clientes corporativos, institucionales e individuos de alta renta como: ',
            a4l1: 'Fusiones y Adquisidores (compra, venta, división y combinación de empresas)',
            a4l2: 'Diseño y colocación de productos estructurados',
            a4l3: '(Re) Estructuración corporativa',


            /* Strategies */
            strats: 'ESTRATEGIAS DE INVERSIÓN',
            stratsdesc: 'La estrategia de inversión es el plan que guía la toma de decisiones de un inversionista y depende de varios factores como la edad, objetivo, plazo, aversión al riesgo, capital entre otros. Sin embargo, existen puntos clave para trazar una estrategia de inversión. ',
            s1: 'DIVERSIFICACIÓN',
            s1d: 'Consiste en no concentrar el capital en un activo o grupo de activos en particular, esto con el objetivo de disminuir el riesgo. Los Fondos Mutuales, así como las E.I.C. se especializan en buscar la disminución del riesgo mediante la diversificación de los activos que componen su portafolio.',
            s2: 'PLAZOS',
            s2d: 'Una inversión puede ser a corto, mediano o largo plazo y el mismo esta atado al riesgo y rendimiento. En este sentido los Fondos suelen ser inversiones a mediano y largo plazo que basan su estrategia en la Inversión en Valor, reduciendo así el riesgo del portafolio.',
            s3: 'PLANIFICACIÓN FISCAL',
            s3d: 'Una manera de maximizar tu potencial rendimiento es minimizando impuestos. Al hacer inversiones fiscalmente inteligentes, puedes reducir el monto perdido ante el fisco cada año manteniendo así mayor cantidad de tus ganancias para cubrir necesidades presentes o futuras. ',
            s3d2: 'Las ganancias netas de las Entidades de Inversión Colectiva están exentas de ISLR, así como también los rendimientos provenientes de inversiones en Fondos Mutuales o de inversión de oferta publica, por eso este tipo de inversión es considerada una inversión fiscalmente inteligente. ',
            s4: 'CAPITAL ',
            s4d: ' El monto del capital a invertir dependerá de la condición de cada inversionista y debería ser proporcional a los ingresos y gastos del mismo. En este sentido es recomendable que cada inversionista mida primero sus ingresos y egresos totales para destinar así un porcentaje de su patrimonio a la inversión y creación de valor. ',

            /* Calendar */
            cal1: 'CALENDARIO BANCARIO 2020',
            cal2: 'CALENDARIO BANCARIO 2019',


            /* Disclaimer */
            dp1: 'Por favor lea cuidadosamente esta información antes de entrar a la página web. Contiene información legal y regulatoria relevante en cuanto a la información contenida en esta página web.',
            dp2: 'PER CAPITAL sociedad Administradora de E.I.C. y los Fondos que ofrece son regulados y han sido autorizados por la SUNAVAL. Los prospectos, información clave, contabilidad y reportes periódicos, así como otros documentos de la sociedad y los fondos que administra pueden ser obtenidos en las oficinas del distribuidor.',
            dp3: 'Si usted es un inversionista Privado ',
            dp4: 'no debe',
            dp5: ' tomar la información contenida en este sitio web como una recomendación o sugerencia que afecte su decisión de inversión. Nada en este sitio web debe ser tomado como una asesoría o consejo financiero.',
            dp6: 'Cada inversionista debe informarse del prospecto, estados financieros y política de inversión antes de invertir.',
            dp7: 'El contenido de este sitio web ha sido preparado basándose en los resultados del análisis de información cuidadosamente levantada, con la opinión de que es confiable para el momento que fue publicada. Las opiniones y visiones presentadas son de PER CAPITAL y pueden cambiar.',
            dp8: 'PER CAPITAL hace uso de las técnicas más adecuadas para asegurar que la información presentada es precisa. Sin embargo, pueden ocurrir errores u omisiones fuera de nuestro control.',
            dp9: 'Bajo ninguna circunstancia se permite la copia o distribución de la información aquí presentada.',
            dp10: 'Asesoría:',
            dp11: 'Nada en este sitio web debe ser considerado como asesoría financiera personal.',
            dp12: 'Desempeño:',
            dp13: 'El desempeño histórico no determina el desempeño a futuro.',
            dp14: 'Fluctuaciones:',
            dp15: 'El valor de los activos pertenecientes a los fondos puede subir o bajar ocasionando fluctuaciones en el valor de la unidad de inversión.',
            dp16: 'Riesgos:',
            dp17: 'Existen riesgos asociados a las inversiones y la perdida de capital es posible.',

            
            /* GRAPH */
            dist: 'DISTRIBUCIÓN POR SECTOR',
            distwhy: '¿Por qué un fondo mutual?',
            distl1: "Acceso a beneficios de portafolio Premium con baja inversión.",
            distl2: 'Ganancias exentas de ISLR.',
            distl3: "Analistas especializados dedicado a gestión del portafolio.",
            distl4: 'Portafolio diversificado para mitigar riesgos.',
            distl5: 'Acceso a precios de economías de escala.',
        },
        en:{
            /* Hotlinks */
            expf: 'Explore Funds',
            exps: 'Explore Services',
            expp: 'FAQ',
            subsbtn: 'Subscribe',

            navB: 'ABOUT US',
            navBD1: 'Why PER CAPITAL?',
            navBD2: 'Team',
            navBD3: 'Corporate Governance',
            navBD4: 'Contact',

            navF: 'FUNDS',
            navFD1: 'Mutual Fund',
            navFD2: 'Real State Fund',
            navFD3: 'Venture Capital',

            navS: 'SERVICES',
            navR: 'REPORTS',
            navRD1: 'Quarterly',
            navRD2: 'Annual',

            navT: 'TOOLS',
            navtD1: 'Calculators',
            navtD2: 'Strategies',
            navtD3: 'News',
            navtD4: 'Calendar',

            
            /* Finally you can start */
            start: 'FINALLY YOU CAN START',
            startdesc: 'PER CAPITAL offers easy access to Premium investment opportunities in the Venezuelan Capital, Real Estate and Venture Capital markets, previously evaluated and approved by our experts, for private, corporate and institutional investors.',
            strans: 'Transaparency',
            stransd: 'We are a regulated company and we meet the highest compliance and management standards to ensure peace of mind for our customers. ',
            sanali:'RIGUROUS ANALYSIS',
            sanalid: 'Our team investigates and analyzes for you, even the smallest detail of each investment project we offer. ',
            sfinance: 'SMART FINANCE',
            sfinanced: 'We study in depth the projects and markets seeking financial solvency, reputation and excellence in business management with the objective of generating value.',
            scomunidad: 'INVESTOR COMMUNITY',
            scomunidadd: 'We build a community of institutional and non-institutional investors that offers a financing alternative. ',
    
            /* Numbers */
            numbers: 'NUMBERS MATTER',
            indicators: 'Indicators',
            pib: 'GDP (%)',
            pob: 'Population (MM)',
            ri: 'International Reserves',
            tc: 'Bs/$',
            te: 'Bs/€',
            ibc: 'IBC',
            co: 'OPEC',
            cv: 'Venezuelan Basket',
            sources: 'Sources',

            /* Calculators */
            calculators: 'CALCULATORS',
            roi: "Investment's rentability",
            ii: 'Initial Investment',
            vf: 'Final Value',
            y: 'Years',
            validationY: 'Data must be numeric, integer, greater than zero',
            result: 'ROI',
            btncalculate: 'Calculate',
            so: 'Saving Goal',
            ia: 'Interest rate (%)',
            p:'Periodicity',
            validationP: 'Select an option',
            resultso: 'R:',

            /* News */
            news: 'NEWS',
        
            /* Contact */
            contact: 'CONTACT',
            location: 'LOCATION',
            phone: 'PHONE',
            email: 'E-MAIL',

            /* Footer */
            fservicesd1: 'Asset Management',
            fservicesd2: 'Financial Advisory',
            fservicesd3: 'Structuring',
            fservicesd4: 'Financial Engineering',
            f1: 'PER CAPITAL Sociedad Administradora de Entidadesde Inversión Colectiva C.A., RIF J-41280239-9 is a company regulated and authorized by SUNAVAL',
            f2: 'PER CAPITAL Fondo Mutual de Inversion de Capital Abierto C.A., RIF is a company regulated and authorized by SUNAVAL ',
            f3: 'PER CAPITAL Asesora de Inversión C.A., RIF J-41296024-5 is a company regulated and authorized by SUNAVAL',
            f4: "PER CAPITAL Asset Management and the Funds it offers are regulated and have been authorized by the SUNAVAL. Prospects, key information, accounting and periodic reports, as well as other company documents and the funds it manages can be obtained at the distributor's offices, via e mail or this website. If you are a Private Investor you",
            f5: 'should not',
            f6: 'take the information contained in this website as a recommendation or suggestion that affects your investment decision. Nothing on this website should be taken as a financial advice or advice. Each investor should be informed of the prospectus, financial statements and investment policy before investing. The content of this website has been prepared based on the results of the carefully collected information analysis, with the opinion that it is reliable for the moment it was published. The opinions and visions presented are of PER CAPITAL and may change. PER CAPITAL makes use of the most appropriate techniques to ensure that the information presented is accurate. However, errors or omissions may occur beyond our control. Under no circumstances is the copy or distribution of the information presented here allowed.',
            f7: 'Advisory:',
            f8: 'Nothing on this website should be considered personal financial advice.',
            f9: 'Performance:',
            f10: 'Historical performance does not determine future performance.',
            f11: 'Fluctuations:',
            f12: 'The value of the assets belonging to the funds may rise or fall causing fluctuations in the value of the investment unit.',
            f13: 'Risks:',
            f14: 'There are risks associated with investments and the loss of capital is possible.',
            f15: 'It should not be assumed nor should it be ensured that the recommended operations will effectively produce the benefits currently estimated, nor that the respective values will in the future behave similarly to the one that underlies this recommendation',
            f16: 'Rules Relating to the Authorization and Registration of Public Brokers of Securities and Investment Advisors. Section V, Article 28.',
            f17: 'There are risks associated with investments, the loss of principal of capital is possible. Some restrictions apply.',
            
            
            /* Why */
            why: 'WHY',
            whydesc: 'We are a team with proven investment and business development experience in the search to grow capital using value investing as strategy. ',
            w1: 'CHOOSE BETWEEN INVESTMENTS DESIGNED FOR EASY EXIT',
            w1d: 'From Mutual Funds to Real Estate Funds, our team of experts thoroughly reviews every detail and makes due diligence for presentation to the public. ',
            w1d1: 'Our goal is to provide our clients with entry and exit facilities for investments. ',
            w2: 'SUPERVISION, CONTROL AND FINANCIAL TRANSPARENCY',
            w2d: 'We maintain continuous evaluation of the assets represented in the investment portfolio, to ensure that they are attached to the business plan. ',
            w2d1: 'Mutual funds are monitored daily to make decisions that mitigate risks and capitalize on capital. Periodic reports are issued to keep our customers informed. ',
            w3: 'EXPERIENCE AND KNOWLEDGE',
            w3d1: 'Our team has extensive and successful investment experience. ',
            w3d2: 'We develop risk coverage strategies to protect us from financial, political and natural crises. ',
            w3d3: 'We know where to invest, how to maximize profits and minimize risks, avoiding abrupt capital decreases. ',

            /* Team */  
            teamdesc: 'Our collective experience of over 40 years, as well as the extensive knowledge in finance, local markets, financial engineering and business development, gives you an advantage when choosing the most suitable investment for you in order to maximize the potential of your capital controlling and minimizing the associated risks.',
            gg: 'GENERAL MANAGER',
            ggd: 'Bank and Finance Administrator and Authorized Investment Advisor with more than 17 years of experience in finance, financial engineering, business development and structuring in local and international markets.',
            f: 'FINANCES',
            fd: 'Business Administrator and Authorized Investment Advisor with more than 17 years of experience in banking and finance, capital markets, trading, portfolio management and risk coverage.',
            ac: 'ADMINISTRATION AND CONTROL ',
            acd: 'C.P.A. and Authorized Investment Advisor with more than 15 years of experience in accounting and financial auditing, projection of financial statements, valuation of companies and administration of financial assets.',
            fc: 'CORPORATE FINANCE',
            fcd: 'Economist, authorized Securities Broker and Investment Advisor with more than 30 years of experience in portfolio management, project evaluation and debt and capital structuring.',
            l: 'LEGAL',
            ld: 'Lawyer with more than 20 years of experience in control and regulation, public management and project development.',
            team: 'TEAM',

            /* Corporate */
            corporate:'CORPORATE GOVERNANCE',
            corporatedesc: 'The PER CAPITAL corporate governance framework is a set of principles, guidelines and practices that support the sustainability of performance and the creation of value for our investors in the long term. Our commitment to good behavior is integral to our business and reflects not only the adherence to regulations and the best standards of the market but also, leadership efficiency of our management.',
            g1: 'Corporate Governance Guide',
            g1d: 'Corporate Governance Guide 2019',
            g2: 'Code of Conduct and Business Ethics',
            g2d: 'Corporate Governance Guide 2019',
            btndownload: 'Download',

            /* Faq */
            faqtit: 'FREQUENTLY ASKED QUESTIONS',
            faqhelp: 'Click on a question to visualize the answer',
            q1: 'What is an Asset Management Company?',
            r1: 'They are companies authorized by SUNAVAL that are intended to administer the assets of collective investment entities, whatever their type, and represent them in accordance with the terms of the administration contract signed for this purpose.',
            r1c: 'Characteristics',
            r1cl: 'They cannot administer to two equal E.I.C.',
            r1cl1: 'Invest resources in the name and on behalf of the E.I.C.',
            r1cl2: 'They charge commissions for services rendered and are set by mutual agreement with E.I.C.',
            r1cl3: 'Keep separate accounts of the E.I.C.',
            r1cl4: 'They keep accounting of the E.I.C.',
            r1cl5: 'Inform quarterly investors of the E.I.C. (state and market behavior)',
            r1cl6: 'Reflect on the profitability of the E.I.C. that manage profitability less expenses and remunerations / commissions.',
            r1np: 'They cannot',
            r1npl: 'Guarantee specific results or yields',
            r1npl1: 'Give or borrow money from the E.I.C',
            r1npl2: 'Maintain custody of bearer securities of the E.I.C.',
            r1npl3: 'Grant personal or real guarantees to secure obligations to third parties',
            r1m: 'They must',
            r1ml: 'Distribute UDI of the E.I.C. ',
            r1ml1: 'Invest resources in the name and account of the E.I.C.',
            r1ml2: 'Maintain continuous evaluation of the values of the E.I.C.',
            r1ml3: 'Ensure that the E.I.C. have cash flow to answer obligations and expenses',
            r1ml4: 'Coordinate legal, accounting and distribution services of the E.I.C.',
            r1ml5: 'Prepare prospects, reports and related reports for investors and SUNAVAL',
            r1ml6: 'Control transfer agent service and provide information to custodian agent for transfer of securities or cash.',
            r1ml7: 'Legally represent the E.I.C.',
            r1ml8: 'Buy IU',
            r1ml9: 'Calculate daily the value of the net amount of mutual funds and their IU',
            r1ml10: 'Keep track of investors and their operations',
            r1ca: 'They can',
            r1cal: 'Withdraw funds from the E.I.C. and its Management Company to pay expenses, repurchase and payment of dividends.',
            r1cal1: 'Act as Investment Advisors, Transfer Agents.',
            q2: 'What is an E.I.C.(Funds)?',
            r2: 'They are entities authorized by SUNAVAL that channel the contributions of investors destined to constitute a common capital, integrated by a portfolio of securities or other assets.',
            r2p: 'They can constitute equity through trust. ',
            r2p2: 'Investors are natural or legal persons with Investment Units. ',
            r2p3: ' Investment Units are shares, or other instruments issued by the E.I.C. ',
            r2c: 'Establish Investment Policy',
            r2c1: 'Define Utility Distribution Policy (capitalize or pay)',
            r2c2: 'Have an investment committee appointed by the entity or by the asset management company.',
            r2c3: 'Investment Committee makes investment decisions',
            r2c4: 'Members of the Investment Committee may be appointed by E.I.C. or by Asset Management Company',
            r2c5: 'They must hold an assembly of investors.',
            r2c6: 'Investors can be represented by power of attorney expressing powers granted.',
            q3: 'What is an Open Capital Mutual Fund?',
            r3: 'It is an E.I.C. which aims at investing in securities, according to the principle of risk distribution. ',
            r3c: 'IU not transferable or registered on the stock exchange (may issue fractions of UDI)',
            r3c1: 'It can increase capital or equity by the contribution of investors or it can decrease equity or capital by withdrawal of investors, without the need for an assembly of investors.',
            r3c2: 'You must distribute the total returns net to investors (in cash or by capitalizing)',
            r3p: 'They can invest in securities: ',
            r3p1: 'Whose public offer has been authorized by the National Securities Commission',
            r3p2: 'Those registered in the stock exchanges',
            r3p3: 'Those that have been issued or endorsed by the Republic or other public law institutions',
            r3p4: 'That they have been issued in accordance with the Law of the Central Bank of Venezuela',
            r3p5: 'Those that have been issued by institutions governed by the General Law of Banks and other Financial Institutions',
            r3p6: 'Those issued according to the Law of the National Savings and Loan System.',
            r3b: 'The net enrichments obtained by collective investment entities and the tax caused',
            r3b2: 'are exempt from income tax.',
            r3b3: 'in accordance with the provisions of the Corporate Asset Tax Law',
            q4: 'What is a Real Estate Fund?',
            r4: 'They are those whose object is channeling of resources towards real estate and real estate projects.',
            q5: 'Why should I invest in PER CAPITAL?',
            r5: 'Access to investment opportunities that were previously only for qualified investors with high assets.',
            r51: 'Benefit from the experience and knowledge of our analysts and team of experts.',
            r52: 'You can start your investment with the minimum required.',
            q6: 'What are the risks?',
            r6: 'Any investment carries risks associated with the market in which it develops. This is due to fluctuations in the market, variables that cannot be controlled or failures in the fulfillment of business plans. ',
            r6p: 'PER CAPITAL evaluates in advance the possible scenarios to try to mitigate as many risks as possible and thus avoid ',
            r6p2: 'However, the risks may exceed the contingency measures taken and the loss of capital is likely. ',
            q7: 'What is the ideal investment for me?',
            r7: 'Investors can choose from the PER CAPITAL product portfolio the fund or investment that best suits their financial goals. In addition, PER CAPITAL has the service of its experts to guide you in the product that best suits your investment objectives. ',
            q8: 'What is the minimum investment?',
            r8: 'The minimum investment will depend on the Fund chosen by the client.',
            q9: 'What are the commissions?',
            r9i: 'Investors',
            r9i1: 'Entry Fee 2.5% when subscribing',
            r9i2: 'Exit Commission 0.0%',
            r9e: 'E.I.C.',
            r9e1: 'Mutual Fund Administration Commission, max 5% of the average value of net assets at closing.',
            r9e2: 'Administration Commission E.I.C. Real estate max 5% of the average value of net assets at closing',
            r9e3: 'Administration Commission E.I.C. Venture Capital max 10% of the average value of net assets at closing',
            q10: 'Once placed my investment how can I see it?',
            r10: 'The client will obtain a certificate for their Investment Units and can see the detail through our website. ',
            q11: 'What requirements should I submit if I am a foreign investor (non-resident)?',
            r11: 'Every foreign investor, whether a Natural or Legal Person, must request a “Non-Resident RIF” from SENIAT by email',
            r11n: 'and present it additionally to general collections.',

            
            /* Mutual */
            mutual: 'OPEN CAPITAL INVESTMENT',
            mutuall: 'I.U.V',
            goal: 'OVERVIEW',
            goaldesc: 'The PER CAPITAL fund Mutual Fund for Open Capital Investment aims to produce medium and long-term capital growth. It mainly invests in shares of companies that are listed, traded and incorporated into the Caracas Stock Exchange, do business and are domiciled',
            goaldesc2:' in Venezuela, as well as in corporate debt securities. Investments may be direct or indirect and the price of the Investment units may vary due to price movements of the securities that make up the portfolio.',
            info: 'KEY FACTS',
            info1: 'Launch Date',
            info2: 'Comparativo',
            info3: 'Benchmark Index',
            info4: 'Pricing',
            info5: 'Minimum Investment',
            info5pill: '1 Investment Unit (IU)',
            info4pill: '14:00 daily',
            risks: 'RISKS',
            risk1: 'The markets subject to investment may rise or fall in price and market conditions may change rapidly. Due to this the value of the Investment Units of a fund may vary in the same way. ',
            rg: 'GENERAL',
            risk2: 'The custody of financial instruments involves risk of loss if the custodian becomes insolvent or fails to comply with his formal duties. The custodian of the Investment Units is the',
            risk2a: 'Caja Venezolana de Valores',
            custody: 'CUSTODY',
            risk3: 'The fund is exposed to the risk of a single market and a single currency. ',
            country: 'COUNTRY',
            risk4: 'The fund has exposure to foreign currencies, so changes in exchange rates can produce increases or decreases in the value of the investment and the profits obtained. ',
            coin: 'CURRENCY/EXCHANGE',
            volatil: 'VOLATILITY',
            risk5: "The price of the Fund's Investment Unit may vary due to the price movement of the assets that comprise it.",
            howt: 'HOW TO INVEST',
            howtd: 'Investing is easy with PER CAPITAL, just follow the steps below and start sowing your future now.',
            pi: 'Investor Profile',
            pid: 'Determine your investor profile taking into account if you are a Natural or Legal Person, age, professional, non-professional and your risk aversion (low, medium, high)',
            pli: 'Investment Term',
            plid: 'Select the desired term for your investment (short, medium or long)',
            fund: 'Fund',
            fundd: 'Select the fund of your choice that best suits your objectives.',
            register: 'Sign up',
            registerd: 'Acquire the desired investment units of the selected fund by completing the compliance process and sending funds for the acquisition. ',
            clickhere: 'Haga clic aquí',
            footer: 'You can also request the Prospectus and the Fact Sheets which will be sent to you via email where you will find the procedure to start. ',
            cfooter:'Contact:',
            btnprospect: 'PROSPECTUS',
            btnreports: 'REPORTS',
            btnsubscribe: 'REGISTER',
            btnsubscribe2: 'SUBSCRIBE',

            /* Services */
            a1tit: 'ASSET MANAGEMENT',
            a1: 'Collective Investment Entities (E.I.C) or Funds are a way of channeling the capital of investors as a common asset for the development of different projects with the objective of obtaining a return.',
            a11: 'PER CAPITAL has authorization of the regulator for the administration of Funds and E.I.C. and puts at your disposal our experience and specialized team to: ',
            a1l1: 'Structure of Funds and E.I.C.',
            a1l2: 'Fund and E.I.C. management',
            a12: 'We structure, administer and place E.I.C., covering risks, ensuring the custody and ownership of related assets, generating value for our clients.',
            a2tit: 'FINANCIAL ADVICE',
            a2: 'We are a regulated and authorized to provide Advisory services; We have professionals with proven experience, certified as Investment Advisors and willing to provide the best service possible.',
            a21: 'Our team focuses on being a guide in the evaluation process and advice for wealth planning and management at the following levels: ',
            a2l1: 'Financial',
            a2l2: 'Legal',
            a2l3: 'Accountant',
            a2l4: 'Tax',
            a22: 'Focused on obtaining results with controlled risks. We help our clients achieve their financial goals ',
            a3tit: 'STRUCTURING',
            a3: 'We carry out projects of (re)structuring, issuance and placement of: ',
            a3l1: 'Fixed income',
            a3l2: 'Variable income',
            a3l3: 'Our work methodology consists of 4 steps: ',
            a3l4: 'Information, diagnosis and evaluation',
            a3l5: 'Authorization of competent bodies',
            a3l6: 'Post registration activities',
            a3l7: 'Placement',
            a32: 'We rely on our network in the local and international capital markets.',
            a4tit: 'FINANCIAL ENGINEERING',
            a4: 'We offer financial solutions for corporate clients, institutional and high-income individuals such as: ',
            a4l1: 'Mergers and Acquirers (purchase, sale, division and combination of companies)',
            a4l2: 'Design and placement of structured products',
            a4l3: '(Re) Corporate structuring',

            
            /* Strategies */
            strats: 'INVESTMENT STRATEGIES',
            stratsdesc: 'The investment strategy is the plan that guides the decision-making process of an investor and depends on several factors such as age, objective, term, risk aversion and capital among others. However, there are key points to draw up an investment strategy.',
            s1: 'DIVERSIFICATION',
            s1d: 'It consists of not concentrating the capital in a particular asset or group of assets, with the objective of reducing the risk. Mutual Funds, as well as the E.I.C., specialize in seeking risk reduction by diversifying the assets that make up their portfolio.',
            s2: 'TERM',
            s2d: 'An investment can be short, medium or long term and it is tied to risk and return. In this sense, the Funds are usually medium and long-term investments that base their strategy on Value Investing, thus reducing portfolio risk.',
            s3: 'TAX PLANNING',
            s3d: 'One way to maximize your potential return is to minimize taxes. By making tax smart investments, you can reduce the amount lost to the tax collector each year thus keeping more of your earnings to cover present or future needs. ',
            s3d2: 'The net incomes of the Collective Investment Entities and Funds are tax exempt, as well as the returns from investments in Mutual Funds or public offering investment, so this type of investment is considered a fiscally smart investment. ',
            s4: 'CAPITAL ',
            s4d: ' The amount of capital to be invested will depend on the condition of each investor and should be proportional to its income and expenses. In this sense, it is recommended that each investor first measure their total income and expenses to allocate a percentage of their assets to the investment and value creation.',
            
            /* Calendar */
            cal1: 'BANK CALENDAR 2020',
            cal2: 'BANK CALENDAR 2019',

            /* Disclaimer */
            dp1: 'Please read this information before entering the website. It contains relevant legal and regulatory information regarding the information contained.',
            dp2: "PER CAPITAL Asset Management and the Funds it offers are regulated and have been authorized by the SUNAVAL. Prospects, key information, accounting and periodic reports, as well as other company documents and the funds it manages can be obtained at the distributor's offices, via e mail or this website.",
            dp3: 'If you are a Private Investor you',
            dp4: 'should not',
            dp5: 'take the information contained in this website as a recommendation or suggestion that affects your investment decision. Nothing on this website should be taken as a financial advice or advice.',
            dp6: 'Each investor should be informed of the prospectus, financial statements and investment policy before investing.',
            dp7: 'The content of this website has been prepared based on the results of the carefully collected information analysis, with the opinion that it is reliable for the moment it was published. The opinions and visions presented are of PER CAPITAL and may change.',
            dp8: 'PER CAPITAL makes use of the most appropriate techniques to ensure that the information presented is accurate. However, errors or omissions may occur beyond our control.',
            dp9: 'Under no circumstances is the copy or distribution of the information presented here allowed.',
            dp10: 'Advisory:',
            dp11: 'Nothing on this website should be considered personal financial advice.',
            dp12: 'Performance:',
            dp13: 'Historical performance does not determine future performance.',
            dp14: 'Fluctuations:',
            dp15: 'The value of the assets belonging to the funds may rise or fall causing fluctuations in the value of the investment unit.',
            dp16: 'Risks:',
            dp17: 'There are risks associated with investments and the loss of capital is possible.',

            /* GRAPH */
            dist: 'DISTRIBUTION BY SECTOR',
            distwhy: 'Why a mutual fund?',
            distl1: "Access to Premium portfolios' benefits with low investment.",
            distl2: 'Tax free earnings.',
            distl3: "Specialized analists dedicated to portfolio's management.",
            distl4: 'Diversified portfolio to ease risks.',
            distl5: 'Access to prices of scale economies.',
        },

    }
})